In [ ]:
from torch.utils.data import Dataset

class CustomDataset(Dataset):
  def __init__(self, np_data, transform=None) -> None:
    super().__init__()
    self.data = np_data
    self.transform = transform
    self.len = np_data.shape[0]
  def __len__(self):
    return self.len
  def __getitem__(self, idx):
    sample = self.data[idx]
    if self.transform:
      sample = self.transform(sample)
      return sample

In [ ]:
import numpy as np
from torch.utils.data import DataLoader
import torchvision.transforms as tr

def square(sample):
  return sample ** 2;
trans = tr.Compose([square])
custom_dataset= CustomDataset(np.arange(10), trans)

In [ ]:
custom_dataloader = DataLoader(custom_dataset, batch_size=2, shuffle=True)

In [ ]:
for _ in range(3):
  for data in custom_dataloader:
    print(data)
  print('=' * 20)

tensor([36,  9])
tensor([49, 81])
tensor([64,  1])
tensor([16, 25])
tensor([0, 4])
tensor([36,  0])
tensor([16, 64])
tensor([ 9, 25])
tensor([1, 4])
tensor([81, 49])
tensor([9, 4])
tensor([81,  1])
tensor([36, 64])
tensor([16,  0])
tensor([49, 25])
